import detect from '~/detect'

find('abc', 'latin')
find('שָׁלוֹם', 'hebrew')
find('美丽的', 'chinese')
find('ひらがな', 'japanese')
find('कल्पना', 'devanagari')
find('قمر', 'arabic')
find('மின்னல்', 'tamil')
find('αποκάλυψη', 'greek')
find('дружба', 'cyrillic')
find('རྣམ་ཤེས་', 'tibetan')
find('ป่า', 'thai')
find('മരം', 'malayalam')
find('ⲁⲛⲁ', 'coptic')
find('𐍅𐌰𐌹𐍂𐌳𐍃', 'gothic')
find('વન', 'gujarati')
find('ტყე', 'georgian')
find('ਬਗੀਚਾ', 'gurmukhi')
find('ᓄᓇ', 'syllabics')
find('ಕಾಡು', 'kannada')
find('산', 'korean')
find('ଜଙ୍ଗଲ', 'oriya')
find('అడవి', 'telugu')
find('արարատ', 'armenian')
find('ተራራ', 'geez')
find('𐬀𐬵𐬀', 'avestan')
find('𒀀𒌑', 'cuneiform')
find('পাহাড়', 'bengali')
find('တောင်း', 'burmese')
find('ꦲꦺꦴꦁ', 'javanese')
find('ព្រៃ', 'khmer')
find('ᠪᠠᠭᠠ', 'mongolian')
find('කඳ', 'sinhala')
find('ᮊᮥᮜ', 'sundanese')
find('ܥܝܢܐ', 'syriac')
find('ⴰⵔⴳⴰⵏ', 'tifinagh')
find('𓆓', 'egyptian')
find('ᬩᬮᬶ', 'balinese')
find('ᨕᨙ', 'buginese')
find('ᎠᎹ', 'cherokee')
find('ດ້ວຍ', 'lao')
find('ᰕᰨ', 'lepcha')
find('ᜀᜅ᜔', 'baybayin')

function find(lead: string, talk: string) {
  const { form, rank } = detect([...lead])
  console.log(`term ${lead}`)
  console.log(`  talk => ${form}`)
  console.log(`  rank => ${rank}`)

  if (form !== talk) {
    throw new Error(`${form} != ${talk}`)
  }
}
