const alphabet = {
  '𐐨': { name: 'Long I', IPA: 'iː' },
  '𐐩': { name: 'Long E', IPA: 'eɪ' },
  '𐐪': { name: 'Long A', IPA: 'ɑː' },
  '𐐫': { name: 'Long Ah', IPA: 'ɔː' },
  '𐐬': { name: 'Long O', IPA: 'oʊ' },
  '𐐭': { name: 'Long Oo', IPA: 'uː' },
  '𐐮': { name: 'Short I', IPA: 'ɪ' },
  '𐐯': { name: 'Short E', IPA: 'ɛ' },
  '𐐰': { name: 'Short A', IPA: 'æ' },
  '𐐱': { name: 'Short Ah', IPA: 'ɒ' },
  '𐐲': { name: 'Short O', IPA: 'ʌ' },
  '𐐳': { name: 'Short Oo', IPA: 'ʊ' },
  '𐐴': { name: 'Ay', IPA: 'aɪ' },
  '𐐵': { name: 'Ow', IPA: 'aʊ' },
  '𐐶': { name: 'Wu', IPA: 'w' },
  '𐐷': { name: 'Yee', IPA: 'j' },
  '𐐸': { name: 'H', IPA: 'h' },
  '𐐹': { name: 'Pee', IPA: 'p' },
  '𐐺': { name: 'Bee', IPA: 'b' },
  '𐐻': { name: 'Tee', IPA: 't' },
  '𐐼': { name: 'Dee', IPA: 'd' },
  '𐐽': { name: 'Chee', IPA: 'tʃ' },
  '𐐾': { name: 'Jee', IPA: 'dʒ' },
  '𐐿': { name: 'Kay', IPA: 'k' },
  '𐑀': { name: 'Gay', IPA: 'ɡ' },
  '𐑁': { name: 'Ef', IPA: 'f' },
  '𐑂': { name: 'Vee', IPA: 'v' },
  '𐑃': { name: 'Eth', IPA: 'θ' },
  '𐑄': { name: 'Thee', IPA: 'ð' },
  '𐑅': { name: 'Es', IPA: 's' },
  '𐑆': { name: 'Zee', IPA: 'z' },
  '𐑇': { name: 'Esh', IPA: 'ʃ' },
  '𐑈': { name: 'Zhee', IPA: 'ʒ' },
  '𐑉': { name: 'Er', IPA: 'r' },
  '𐑊': { name: 'El', IPA: 'l' },
  '𐑋': { name: 'Em', IPA: 'm' },
  '𐑌': { name: 'En', IPA: 'n' },
  '𐑍': { name: 'Eng', IPA: 'ŋ' },
  '𐑎': { name: 'Oi', IPA: 'ɔɪ' },
  '𐑏': { name: 'Ew', IPA: 'juː' },
}
